### ISSUE TITLE
constructor never returns -- no network timeout

### ISSUE THREAD

**Issue by dulitz** [craigjmidwinter/total-connect-client#134]
zeep [suggests](https://docs.python-zeep.org/en/master/transport.html#session-timeout) that there is a default timeout of 300 seconds for all sessions. But this doesn't seem to be the case.

This morning we had a network disaster, which caused our containers to bounce. When they came back up there was no external connectivity. The TotalConnectClient constructor was called every minute, and 10 seconds after it was called it raised `ConnectionError` due to a failure in name resolution.

So far so good.

But after about 130 of those calls to the constructor, one of the calls to the constructor simply hung. It was called at 7:51:13 PDT and now more than 12 hours later it has neither returned nor raised an exception.

In a multithreaded process, all the other threads have been happily doing network I/O since 8:45am PDT or so.

Unfortunately this is with the release prior to the most recent one (see issue #133 ) so there's a lot going on in the constructor. But still, if there was any timeout at all one of the zeep requests should have failed by now.

I have seen this issue before with TotalConnectClient, always during network turbulence (when is when you really want a timeout).

**Comment by dulitz** [comment]
This was observed on code that is now very different from the current code. I will reopen the issue if I observe it again.

**Comment by dulitz** [comment]
Observed again with latest release. I have a critical section that runs
```
for loc in client.locations:
  loc.get_partition_details()
  loc.get_zone_details()
  loc.get_panel_meta_data()
```
and I've been stuck in that critical section for over 24 hours now.

At process start, I created two clients. Their constructors both returned, so we successfully authenticated. We then very quickly got 'retrying connection error' on one of them (logging doesn't say which), which retried 5 times and then apparently succeeded since it didn't retry a sixth time.

Then a few minutes later we got 'retrying failed to connect with panel' on one of them (don't know which), which retried 5 times with 'retrying connection error' and then apparently succeeded.

Then we got 'retrying connection error' again which retried 3 times and apparently succeeded.

And then we got stuck in that critical section.

So we are clearly having connectivity issues between us and alarmnet. Our retry logic is working as well as can be expected. But then we get stuck in zeep.

**Comment by austinmroczek** [comment]
We're doing everything with synchronous IO so there aren't overlapping requests ongoing.  Simple way to add better log info would be to have client.request() store a client._last_request that we could dump into the log during raise for retry/result.  Other route would be to add a "source" variable for raise for retry/result that gets added to the log.

**Comment by austinmroczek** [comment]
Separate thing to consider is trying to catch certain exceptions to highlight problems to users.

I got this one yesterday during the few minutes my router was down for an update.

```txt
Logger: homeassistant.helpers.entity
Source: components/totalconnect/alarm_control_panel.py:77
First occurred: September 5, 2021, 1:37:43 PM (1 occurrences)
Last logged: September 5, 2021, 1:37:43 PM

Update for alarm_control_panel.home1 fails
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/srv/homeassistant/lib/python3.9/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/srv/homeassistant/lib/python3.9/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.9/http/client.py", line 1347, in getresponse
    response.begin()
  File "/usr/local/lib/python3.9/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.9/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/lib/python3.9/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/local/lib/python3.9/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
OSError: [Errno 113] No route to host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/srv/homeassistant/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/srv/homeassistant/lib/python3.9/site-packages/urllib3/util/retry.py", line 531, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/srv/homeassistant/lib/python3.9/site-packages/urllib3/packages/six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "/srv/homeassistant/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/srv/homeassistant/lib/python3.9/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/srv/homeassistant/lib/python3.9/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.9/http/client.py", line 1347, in getresponse
    response.begin()
  File "/usr/local/lib/python3.9/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.9/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/lib/python3.9/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/local/lib/python3.9/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
urllib3.exceptions.ProtocolError: ('Connection aborted.', OSError(113, 'No route to host'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/entity.py", line 446, in async_update_ha_state
    await self.async_device_update()
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/entity.py", line 649, in async_device_update
    await task
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/components/totalconnect/alarm_control_panel.py", line 77, in update
    self._client.get_armed_status(self._location_id)
  File "/srv/homeassistant/lib/python3.9/site-packages/total_connect_client/TotalConnectClient.py", line 445, in get_armed_status
    self.get_panel_meta_data(location_id)
  File "/srv/homeassistant/lib/python3.9/site-packages/total_connect_client/TotalConnectClient.py", line 411, in get_panel_meta_data
    result = self.request(
  File "/srv/homeassistant/lib/python3.9/site-packages/total_connect_client/TotalConnectClient.py", line 134, in request
    response = eval(self.soap_base + request)
  File "<string>", line 1, in <module>
  File "/srv/homeassistant/lib/python3.9/site-packages/zeep/proxy.py", line 46, in __call__
    return self._proxy._binding.send(
  File "/srv/homeassistant/lib/python3.9/site-packages/zeep/wsdl/bindings/soap.py", line 127, in send
    response = client.transport.post_xml(options["address"], envelope, http_headers)
  File "/srv/homeassistant/lib/python3.9/site-packages/zeep/transports.py", line 107, in post_xml
    return self.post(address, message, headers)
  File "/srv/homeassistant/lib/python3.9/site-packages/zeep/transports.py", line 73, in post
    response = self.session.post(
  File "/srv/homeassistant/lib/python3.9/site-packages/requests/sessions.py", line 590, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/srv/homeassistant/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/srv/homeassistant/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/srv/homeassistant/lib/python3.9/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', OSError(113, 'No route to host'))


```

Ones like this would be good to tell users it's your problem, vice internet/TotalConnect problem.

**Comment by dulitz** [comment]
That might be a good idea but I don't think it will help here. I don't think the behavior has anything to do with the form of the request -- and even if it was caused by a particular request form, it wouldn't matter, because timeouts can still happen and zeep needs to give up and fail eventually.

And... I just looked at the zeep docs -- different docs than I looked at before. https://docs.python-zeep.org/en/master/transport.html

They are clear that in various cases zeep has no timeouts. I will send you a PR for the use of an explicit transport with timeouts.

**Comment by dulitz** [comment]
Re: catching exceptions to highlight to the user. I think total-connect-client is the wrong level at which to do that. Presumably if there's an overall routing problem, the user should be seeing things failing in lots of code they're running. So they should figure it out.

Meanwhile many errors -- even no route to host -- are transient and we might even manage to succeed after retrying. So I think it's really hard to do this for little payoff.

**Comment by dulitz** [comment]
I think this is closed now too with the merge this morning. I will reopen it if I see it again, though presumably if I see it again it will be for a different reason?
