### ISSUE TITLE
Location arming_state must handle value 10214

### ISSUE THREAD

**Issue by austinmroczek** [craigjmidwinter/total-connect-client#144]
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.9/site-packages/total_connect_client/__main__.py", line 24, in <module>
    print(TC)
  File "/usr/local/lib/python3.9/site-packages/total_connect_client/client.py", line 125, in __str__
    locations = f"LOCATIONS: {len(self.locations)}\n\n"
  File "/usr/local/lib/python3.9/site-packages/total_connect_client/client.py", line 99, in locations
    location.get_panel_meta_data()
  File "/usr/local/lib/python3.9/site-packages/total_connect_client/location.py", line 111, in get_panel_meta_data
    self.set_status(result)
  File "/usr/local/lib/python3.9/site-packages/total_connect_client/location.py", line 130, in set_status
    self.arming_state = ArmingState(astate)
  File "/usr/local/lib/python3.9/enum.py", line 384, in __call__
    return cls.__new__(cls, value)
  File "/usr/local/lib/python3.9/enum.py", line 702, in __new__
    raise ve_exc
ValueError: 10214 is not a valid ArmingState
```

My location arming_state (which the code previously ignored because it just grabbed partition 1 arming_state) is returning 10214.  

Following live tests with the system, it appears that location.arming_state is 10214 when disarmed with one or more zones faulted, or "disarmed not ready to arm" as my Lynx 7000 panel says.

Partition.arming_state remains DISARMED when disarmed and when disarmed with zones faulted.

**Comment by austinmroczek** [comment]
working on a fix

**Comment by austinmroczek** [comment]
@dulitz I fixed this by handling the code we were missing, but is there a way to have ArmingState catch the error if it doesn't hold that value?  We need to give users a human-readable message to report the new code to us.

**Comment by dulitz** [comment]
Yes there is a way. PR coming tonight. Same issue for the other enums
actually.
