### ISSUE TITLE
More authentication weirdness

### ISSUE THREAD

**Issue by austinmroczek** [craigjmidwinter/total-connect-client#232]
Log from HA following purposeful entry of an invalid password.

The weird thing is this seems to be opposite of what was seen in #180 in the past.  Need to review that issue more carefully.

```txt
Logger: homeassistant.config_entries
Source: config_entries.py:640
First occurred: 4:44:50 PM (1 occurrences)
Last logged: 4:44:50 PM

Error setting up entry Total Connect for totalconnect
Traceback (most recent call last):
  File "/workspaces/home-assistant/homeassistant/config_entries.py", line 640, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/home-assistant/homeassistant/components/totalconnect/__init__.py", line 36, in async_setup_entry
    client = await hass.async_add_executor_job(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/ha-venv/lib/python3.12/site-packages/total_connect_client/client.py", line 96, in __init__
    self.authenticate()
  File "/home/vscode/.local/ha-venv/lib/python3.12/site-packages/total_connect_client/client.py", line 296, in authenticate
    response = self.request(
               ^^^^^^^^^^^^^
  File "/home/vscode/.local/ha-venv/lib/python3.12/site-packages/total_connect_client/client.py", line 279, in request
    return self.request(operation_name, args, attempts_remaining)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/ha-venv/lib/python3.12/site-packages/total_connect_client/client.py", line 279, in request
    return self.request(operation_name, args, attempts_remaining)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/ha-venv/lib/python3.12/site-packages/total_connect_client/client.py", line 279, in request
    return self.request(operation_name, args, attempts_remaining)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  [Previous line repeated 1 more time]
  File "/home/vscode/.local/ha-venv/lib/python3.12/site-packages/total_connect_client/client.py", line 235, in request
    self._raise_for_retry(response)
  File "/home/vscode/.local/ha-venv/lib/python3.12/site-packages/total_connect_client/client.py", line 167, in _raise_for_retry
    raise RetryableTotalConnectError(
total_connect_client.exceptions.RetryableTotalConnectError: ('temporary authentication failure', OrderedDict({'ResultCode': -100, 'ResultData': 'Authentication Failed', 'ModuleFlags': None, 'SessionID': None, 'PrivacyStatementUrl': None, 'UserInfo': None, 'Locations': None, 'InterfaceSchemaConfigInfo': None}))
```

**Comment by austinmroczek** [comment]
As-is a -100/AUTHENTICATION_FAILED result code results in a RetryableTotalConnectError exception, so we keep hammering the server with the bad password.  This then results in #231 and the account gets locked.  And because HA thinks it's retryable, it just keeps trying (woke up this morning and my email inbox is filled with "your account is locked" messages)

Per #180 it's possible that flaky internet could give this result code, and result in users having to re-authenticate in HA even though the password is not really bad.  It's also possible that something changed on the server side and this is how they respond to bad passwords now (instead of -50004). 

Re-authenticating with a valid password is annoying, but less annoying than an inbox full of messages.

PR #233 will make a -100 result code raise AuthenticationError.
