### ISSUE TITLE
-4104 Failed to Connect with Security System

### ISSUE THREAD

**Issue by austinmroczek** [craigjmidwinter/total-connect-client#55]
Looks like another new result code, and further issues with connectivity with Total Connect.  I will look into this.

```txt
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/setup.py", line 170, in _async_setup_component
    hass, processed_config
  File "/home/homeassistant/.homeassistant/custom_components/totalconnect/__init__.py", line 40, in async_setup
    client = TotalConnectClient.TotalConnectClient(username, password)
  File "/srv/homeassistant/lib/python3.7/site-packages/total_connect_client/TotalConnectClient.py", line 81, in __init__
    self.authenticate()
  File "/srv/homeassistant/lib/python3.7/site-packages/total_connect_client/TotalConnectClient.py", line 119, in authenticate
    self.populate_details(response)
  File "/srv/homeassistant/lib/python3.7/site-packages/total_connect_client/TotalConnectClient.py", line 143, in populate_details
    self.get_zone_details(location["LocationID"])
  File "/srv/homeassistant/lib/python3.7/site-packages/total_connect_client/TotalConnectClient.py", line 411, in get_zone_details
    + str(result["ResultData"])
Exception: Could not retrieve zone detail data. ResultCode: -4104. ResultData: Failed to Connect with Security System
```

**Comment by uchagani** [comment]
Appreciate you working on these @austinmroczek . I can push up a new release whenever you're ready
