### ISSUE TITLE
location.set_status() gives AttributeError 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by austinmroczek** [craigjmidwinter/total-connect-client#95]
From https://github.com/home-assistant/core/issues/37983

AttributeError 'NoneType' object has no attribute 'get'

```txt
Logger: homeassistant.helpers.entity
Source: components/totalconnect/alarm_control_panel.py:73
First occurred: July 18, 2020, 9:58:03 PM (1 occurrences)
Last logged: July 18, 2020, 9:58:03 PM
Update for alarm_control_panel.home1 fails

Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/entity.py", line 272, in async_update_ha_state
    await self.async_device_update()
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/entity.py", line 466, in async_device_update
    self.update  # type: ignore
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/totalconnect/alarm_control_panel.py", line 73, in update
    self._client.get_armed_status(self._location_id)
  File "/srv/homeassistant/lib/python3.7/site-packages/total_connect_client/TotalConnectClient.py", line 390, in get_armed_status
    self.get_panel_meta_data(location_id)
  File "/srv/homeassistant/lib/python3.7/site-packages/total_connect_client/TotalConnectClient.py", line 372, in get_panel_meta_data
    self.locations[location_id].set_status(result["PanelMetadataAndStatus"])
  File "/srv/homeassistant/lib/python3.7/site-packages/total_connect_client/TotalConnectClient.py", line 570, in set_status
    self.ac_loss = data.get("IsInACLoss")
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by austinmroczek** [comment]
Fixed in 0.56
