### ISSUE TITLE
Error during setup of component totalconnect

### ISSUE THREAD

**Issue by djp2squared** [craigjmidwinter/total-connect-client#96]
My Total Connect client just recently stopped working 4 days ago. I am running Ver. 0.108.2 Here is the error im getting.

Logger: homeassistant.setup
Source: components/totalconnect/__init__.py:37
First occurred: July 26, 2020, 7:53:21 PM (1 occurrences)
Last logged: July 26, 2020, 7:53:21 PM

Error during setup of component totalconnect
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 175, in _async_setup_component
    component.setup, hass, processed_config  # type: ignore
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/totalconnect/__init__.py", line 37, in setup
    client = TotalConnectClient.TotalConnectClient(username, password)
  File "/usr/local/lib/python3.7/site-packages/total_connect_client/TotalConnectClient.py", line 75, in __init__
    self.authenticate()
  File "/usr/local/lib/python3.7/site-packages/total_connect_client/TotalConnectClient.py", line 139, in authenticate
    self.populate_details(response)
  File "/usr/local/lib/python3.7/site-packages/total_connect_client/TotalConnectClient.py", line 187, in populate_details
    self.get_zone_details(location_id)
  File "/usr/local/lib/python3.7/site-packages/total_connect_client/TotalConnectClient.py", line 415, in get_zone_details
    + ', {"int": ["1"]}, 0)'
  File "/usr/local/lib/python3.7/site-packages/total_connect_client/TotalConnectClient.py", line 97, in request
    return self.request(request, attempts)
  File "/usr/local/lib/python3.7/site-packages/total_connect_client/TotalConnectClient.py", line 97, in request
    return self.request(request, attempts)
  File "/usr/local/lib/python3.7/site-packages/total_connect_client/TotalConnectClient.py", line 97, in request
    return self.request(request, attempts)
  [Previous line repeated 7 more times]
  File "/usr/local/lib/python3.7/site-packages/total_connect_client/TotalConnectClient.py", line 120, in request
    "total-connect-client could not execute request.  Maximum attempts tried."
Exception: total-connect-client could not execute request.  Maximum attempts tried.

**Comment by austinmroczek** [comment]
@djp2squared sorry you've run into this issue.  Are you still having trouble today?  Since this failed during Home Assistant setup, you'll likely need to restart Home Assistant to see if it works now.

It could be a temporary issue with TotalConnect, or perhaps a temporary issue with your internet.  

Please follow the troubleshooting instructions at https://github.com/craigjmidwinter/total-connect-client and post your info here.  Be sure to remove your account information.

**Comment by austinmroczek** [comment]
@djp2squared has it started working?  Please let us know so we can either close out this issue, or help resolve your problem.

**Comment by djp2squared** [comment]
Yep started working 2 days ago after a few restarts, weird but so far so good. Thanks.
