### ISSUE TITLE
Zeep XML Error in Home Assistant

### ISSUE THREAD

**Issue by schmittx** [craigjmidwinter/total-connect-client#98]
After a recent restart of Home Assistant, I started getting the error below. I've tried multiple restarts over the past ~24hours and the error still persists.

Is anyone else experiencing the same? I'm not very familiar with Zeep so I don't have a great idea of where the problem lies, but I'm guessing the `rs.alarmnet.com` page may have changed?

```
Logger: homeassistant.config_entries
Source: custom_components/totalconnect/__init__.py:58
First occurred: 10:15:08 AM (1 occurrences)
Last logged: 10:15:08 AM

Error setting up entry Total Connect for totalconnect
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/zeep/loader.py", line 49, in parse_xml
    return fromstring(
  File "/usr/local/lib/python3.8/site-packages/defusedxml/lxml.py", line 145, in fromstring
    rootelement = _etree.fromstring(text, parser, base_url=base_url)
  File "src/lxml/etree.pyx", line 3237, in lxml.etree.fromstring
  File "src/lxml/parser.pxi", line 1896, in lxml.etree._parseMemoryDocument
  File "src/lxml/parser.pxi", line 1784, in lxml.etree._parseDoc
  File "src/lxml/parser.pxi", line 1141, in lxml.etree._BaseParser._parseDoc
  File "src/lxml/parser.pxi", line 615, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 725, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 654, in lxml.etree._raiseParseError
  File "https://rs.alarmnet.com/TC21api/tc2.asmx?WSDL", line 1
lxml.etree.XMLSyntaxError: StartTag: invalid element name, line 1, column 2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 231, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/totalconnect/__init__.py", line 58, in async_setup_entry
    client = await hass.async_add_executor_job(
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/site-packages/total_connect_client/TotalConnectClient.py", line 58, in __init__
    self.soapClient = zeep.Client("https://rs.alarmnet.com/TC21api/tc2.asmx?WSDL")
  File "/usr/local/lib/python3.8/site-packages/zeep/client.py", line 68, in __init__
    self.wsdl = Document(wsdl, self.transport, settings=self.settings)
  File "/usr/local/lib/python3.8/site-packages/zeep/wsdl/wsdl.py", line 82, in __init__
    root_definitions = Definition(self, document, self.location)
  File "/usr/local/lib/python3.8/site-packages/zeep/wsdl/wsdl.py", line 184, in __init__
    self.parse_types(doc)
  File "/usr/local/lib/python3.8/site-packages/zeep/wsdl/wsdl.py", line 316, in parse_types
    self.types.add_documents(schema_nodes, self.location)
  File "/usr/local/lib/python3.8/site-packages/zeep/xsd/schema.py", line 113, in add_documents
    document = self.create_new_document(node, location)
  File "/usr/local/lib/python3.8/site-packages/zeep/xsd/schema.py", line 213, in create_new_document
    schema.load(self, node)
  File "/usr/local/lib/python3.8/site-packages/zeep/xsd/schema.py", line 440, in load
    visitor.visit_schema(node)
  File "/usr/local/lib/python3.8/site-packages/zeep/xsd/visitor.py", line 160, in visit_schema
    self.process(child, parent=node)
  File "/usr/local/lib/python3.8/site-packages/zeep/xsd/visitor.py", line 88, in process
    result = visit_func(self, node, parent)
  File "/usr/local/lib/python3.8/site-packages/zeep/xsd/visitor.py", line 617, in visit_complex_type
    kwargs = self.visit_complex_content(children[0], node)
  File "/usr/local/lib/python3.8/site-packages/zeep/xsd/visitor.py", line 661, in visit_complex_content
    base, element, attributes = self.visit_restriction_complex_content(
  File "/usr/local/lib/python3.8/site-packages/zeep/xsd/visitor.py", line 775, in visit_restriction_complex_content
    base_type = self._get_type(base_name)
  File "/usr/local/lib/python3.8/site-packages/zeep/xsd/visitor.py", line 1201, in _get_type
    name = self._create_qname(name)
  File "/usr/local/lib/python3.8/site-packages/zeep/xsd/visitor.py", line 1223, in _create_qname
    self.visit_import(import_node, None)
  File "/usr/local/lib/python3.8/site-packages/zeep/xsd/visitor.py", line 233, in visit_import
    schema_node = load_external(
  File "/usr/local/lib/python3.8/site-packages/zeep/loader.py", line 79, in load_external
    return parse_xml(content, transport, base_url, settings=settings)
  File "/usr/local/lib/python3.8/site-packages/zeep/loader.py", line 57, in parse_xml
    raise XMLSyntaxError(
zeep.exceptions.XMLSyntaxError: Invalid XML content received (StartTag: invalid element name, line 1, column 2)
```

**Comment by austinmroczek** [comment]
I’ll look into it tonight

**Comment by schmittx** [comment]
I'm currently on 0.116.1, but I'm fairly certain I noticed the issue once or twice on 0.115.4 just before I upgraded. I believe 0.115.4 is also Python 3.8...

**Comment by schmittx** [comment]
You can disregard this, the problem turned out to be on my end.

My Eero Pro firmware updated automatically recently and the Advanced Security setting was causing this error. I've had it enabled for months now with no problems, but the firmware update must've labeled the `rs.alarmnet.com` as a bad site? I was able to resolve this error by disabling Advanced Security for now.

**Comment by austinmroczek** [comment]
Can you whitelist the server address in your firewall?  Seems odd that a stateful packet inspection firewall (most modern ones) would block the response when a device inside the network initiated the link.

**Comment by schmittx** [comment]
No, Eero seems to have limited ability for granular control. I've contacted them in hopes of working out a better, permanent solution.
